version: "3"

services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$PASSWORD
      - MONGO_INITDB_DATABASE=$DATABASE
    restart: unless-stopped
    ports:
      - $PORT_CONTAINER_DB:$PORT_CONTAINER_DB_EXPOSE
    volumes:
      - ./data/mongo:/data/mongo
    networks:
      - shopper-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb+srv://$USER:$PASSWORD@$HOST_DB_SERVER/?retryWrites=true&w=majority&appName=$DATABASE
      - ME_CONFIG_BASICAUTH_USERNAME=$BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$BASICAUTH_PASSWORD
    restart: unless-stopped
    ports:
      - $PORT_CONTAINER_EXPRESS:$PORT_CONTAINER_EXPRESS_EXPOSE
    depends_on:
      - "mongo"
    networks:
      - shopper-network

  api:
    container_name: api
    build:
      context: "./"
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3333:3333

networks:
  shopper-network:
    driver: bridge